### PR TITLE
Exception consistency (pt.1). Stateless schema validator

### LINKED ISSUE #14: [Feature] Incapsulate exceptions
Currently not only library exceptions are being thrown while validation, but also `respect/validation` library exception comes to the end user like

```
All of the required rules must pass for 18497
```
(expecting `int[]` here, not `int`)

It's very hard to manually process these exceptions and enrich their messages with things like validation data path where the error occured and also make end user create complex try..catch blocks.

I suggest to rethrow these exceptions and thus totally isolate end user from the used validation library knownledge. This will make library usage easier and allows further refactoring without being bond to the validation library because of exception contracts.

Also, at the moment, `respect/validation` exceptions should be part of `validate` method signature, since they are thrown and should be catched

### PR DESCRIPTION
**Pull request by scaytrase**
Key changes:
* Validator instance is now statless. It can be re-used to validate other data against other schema.
* Consistent `\Schema\Exception`
  * new exception class - InvalidSchema - for converting defensive respect validations. It's considered Runtime, so not reflected in sigatures as defencive check
  * new exception class - SchemaMismatch - as a base class for all other validation exceptions
  * new exception hierarchy
     * SchemaMismatch
         * supports breadcrumbs on this level
     * ValidationKeywordFailed (I find this naming strange, but didn't touch it)
     * TypeMismatch (keyword === type)
     * FormatMismatch (keyword === type)
* Validator interface

Also I've updated all signatures in `\Schema` namespace to reflect real exceptions that are expected as validation result.

Fixes #14, partially #18

### CODE REVIEW

File: src/PSR7/Validators/QueryArguments.php [hunk 1]
```diff
@@ -26,18 +29,19 @@ public function validate(MessageInterface $message, array $specs) : void
...
      * @param Parameter[] $specs
+     *
+     * @throws ValidationKeywordFailed
      */
     private function validateServerRequest(ServerRequestInterface $message, array $specs) : void
     {
         // Check if message misses query argument
         foreach ($specs as $name => $spec) {
-            if (! array_key_exists($name, $message->getQueryParams()) && $spec->required) {
+            if ($spec->required && ! array_key_exists($name, $message->getQueryParams())) {
```
Comment (scaytrase) [inline src/PSR7/Validators/QueryArguments.php:44]: just a microoptimisation

File: src/Schema/Keywords/MultipleOf.php [hunk 2]
```diff
@@ -18,18 +18,21 @@ class MultipleOf extends BaseKeyword
...
     public function validate($data, $multipleOf) : void
     {
         try {
             Validator::numeric()->assert($data);
             Validator::numeric()->positive()->assert($multipleOf);
 
-            if ($data % $multipleOf) {
-                throw new Exception(sprintf('Division by %d did not resulted in integer', $multipleOf));
+            $value = $data / $multipleOf;
+            if ((int) $value !== $value) {
```
Comment (scaytrase) [inline src/Schema/Keywords/MultipleOf.php]: https://swagger.io/docs/specification/data-models/data-types/#multipleOf

`multipleOf` could be used against floats, so I patched this a bit while inspecting validator

File: src/Schema/Keywords/Not.php [hunk 3]
```diff
@@ -35,23 +35,25 @@ public function __construct(CebeSchema $parentSchema, int $type, BreadCrumb $bre
...
-                $schemaValidator->validate();
+            $schemaValidator = new SchemaValidator($this->validationDataType);
 
-                throw new Exception(sprintf('Data must not match the schema'));
-            } catch (ValidationKeywordFailed $e) {
-                // that did not match... its ok
+            try {
+                $schemaValidator->validate($data, $not, $this->dataBreadCrumb);
+            } catch (SchemaMismatch $e) {
+                return;
```
Comment (scaytrase) [inline src/Schema/Keywords/Not.php]: Simplified flow here a bit

File: src/Schema/Keywords/OneOf.php [hunk 4]
```diff
@@ -47,23 +50,22 @@ public function validate($data, array $oneOf) : void
             Validator::each(Validator::instance(CebeSchema::class))->assert($oneOf);
 
             // Validate against all schemas
-            $matchedCount = 0;
+            $matchedCount    = 0;
+            $schemaValidator = new SchemaValidator($this->validationDataType);
```
Comment (scaytrase) [inline src/Schema/Keywords/OneOf.php]: With stateless `SchemaValidator` we can instantiate it once

File: src/Schema/Keywords/Required.php [hunk 5]
```diff
@@ -52,23 +55,27 @@ public function validate($data, array $required) : void
                 if (! $propertyFound) {
                     // respect writeOnly/readOnly keywords
                     if ((
-                            $this->parentSchema->properties[$reqProperty]->writeOnly &&
-                            $this->validationDataType === \OpenAPIValidation\Schema\Validator::VALIDATE_AS_RESPONSE
+                            ($this->parentSchema->properties[$reqProperty]->writeOnly ?? false) &&
```
Comment (scaytrase) [inline src/Schema/Keywords/Required.php]: small inline bugfix for unset fields or parent properties

File: src/Schema/Keywords/Type.php [hunk 6]
```diff
@@ -33,70 +32,68 @@ class Type extends BaseKeyword
...
+                    throw TypeMismatch::becauseTypeDoesNotMatch(CebeType::INTEGER, $data);
+                }
+                break;
+            case CebeType::STRING:
+                if (! is_string($data)) {
+                    throw TypeMismatch::becauseTypeDoesNotMatch(CebeType::STRING, $data);
+                }
+                break;
+            default:
+                throw InvalidSchema::becauseTypeIsNotKnown($type);
```
Comment (scaytrase) [inline src/Schema/Keywords/Type.php:73]: Now it's also invalid schema situation, so changed the exception

File: src/Schema/Keywords/UniqueItems.php [hunk 7]
```diff
@@ -25,17 +24,23 @@ class UniqueItems extends BaseKeyword
      * value false.
      *
      * @param mixed $data
+     *
+     * @throws ValidationKeywordFailed
      */
     public function validate($data, bool $uniqueItems) : void
     {
+        if (! $uniqueItems) {
```
Comment (scaytrase) [inline src/Schema/Keywords/UniqueItems.php:32]: Also small bugfix. `uniqueItems` could be set to `false` explicitly

File: src/Schema/Validator.php [hunk 8]
```diff
@@ -4,173 +4,15 @@
...
-            $e->hydrateDataBreadCrumb($this->prepareBreadCrumb());
-            throw $e;
-        }
-    }
-
-    protected function prepareBreadCrumb() : BreadCrumb
-    {
-        return $this->dataBreadCrumb ?? new BreadCrumb();
-    }
+    public function validate($data, Schema $schema, ?BreadCrumb $breadCrumb = null) : void;
```
Comment (scaytrase) [inline src/Schema/Validator.php:17]: As a future idea i suggest to replace third argument to some kind of `ValidationContext` instead (not in this PR). WDYT?

File: tests/Schema/Keywords/TypeTest.php [hunk 9]
```diff
@@ -62,11 +62,8 @@ public function testItValidatesTypeRed() : void
 
             $schema = $this->loadRawSchema($spec);
 
-            try {
-                (new Validator($schema, $invalidValue))->validate();
-            } catch (ValidationKeywordFailed $e) {
-                $this->assertEquals('type', $e->keyword());
-            }
+            $this->expectException(TypeMismatch::class);
```
Comment (scaytrase) [inline tests/Schema/Keywords/TypeTest.php:65]: Some tests becase a bit more clear, where exception inspection is not needed

File: src/Schema/Keywords/MultipleOf.php [hunk 10]
```diff
@@ -18,18 +18,21 @@ class MultipleOf extends BaseKeyword
...
     public function validate($data, $multipleOf) : void
     {
         try {
             Validator::numeric()->assert($data);
             Validator::numeric()->positive()->assert($multipleOf);
 
-            if ($data % $multipleOf) {
-                throw new Exception(sprintf('Division by %d did not resulted in integer', $multipleOf));
+            $value = $data / $multipleOf;
+            if ((int) $value != $value) {
```
Comment (scaytrase) [inline src/Schema/Keywords/MultipleOf.php]: We have a problem here though. `phpcs` requires strict comparison. I'll think how to fix it

File: src/Schema/Keywords/AnyOf.php [hunk 11]
```diff
@@ -39,31 +39,29 @@ public function __construct(CebeSchema $parentSchema, int $type, BreadCrumb $bre
...
-                $breadCrumb      = $this->dataBreadCrumb;
-                $schemaValidator = new SchemaValidator($schema, $data, $this->validationDataType, $breadCrumb);
+                $schemaValidator = new SchemaValidator($this->validationDataType);
                 try {
-                    $schemaValidator->validate();
-                    $matchedCount++;
-                } catch (ValidationKeywordFailed $e) {
+                    $schemaValidator->validate($data, $schema, $this->dataBreadCrumb);
+
+                    return;
```
Comment (scaytrase) [inline src/Schema/Keywords/AnyOf.php]: Simplified flow. We do not really need to continue here if we match something

File: src/PSR7/Validators/QueryArguments.php (hunk 1 above)
Comment (lezhnev74) [reply src/PSR7/Validators/QueryArguments.php:44]: Good catch!

**Comment by lezhnev74** [comment]
@scaytrase I need to collaborate with you on this PR. Is it possible to have write access to the repo, so I can just commit directly here?

**Comment by scaytrase** [comment]
I hope checkbox `allow edits from maintainers` has already granted you this acess. I think you've already fixed my PRs before by adding commits there. But if you need more permissions I'll give you them for sure

File: tests/Schema/Keywords/MultipleOfTest.php [hunk 12]
```diff
@@ -5,39 +5,76 @@
 namespace OpenAPIValidationTests\Schema\Keywords;
 
 use OpenAPIValidation\Schema\Exception\ValidationKeywordFailed;
-use OpenAPIValidation\Schema\Validator;
+use OpenAPIValidation\Schema\SchemaValidator;
 use OpenAPIValidationTests\Schema\SchemaValidatorTest;
 
 final class MultipleOfTest extends SchemaValidatorTest
```
Comment (lezhnev74) [inline tests/Schema/Keywords/MultipleOfTest.php:11]: Please review this test. It fails at the moment.

File: src/Schema/Keywords/Not.php (hunk 3 above)
Comment (lezhnev74) [reply src/Schema/Keywords/Not.php]: Looks good!

File: src/Schema/Keywords/OneOf.php (hunk 4 above)
Comment (lezhnev74) [reply src/Schema/Keywords/OneOf.php]: Good for performance, indeed.

File: src/Schema/Keywords/Required.php (hunk 5 above)
Comment (lezhnev74) [reply src/Schema/Keywords/Required.php]: Good catch. That would have troubled us in the future.

File: src/Schema/Keywords/Type.php (hunk 6 above)
Comment (lezhnev74) [reply src/Schema/Keywords/Type.php:73]: Makes sense

File: src/Schema/Keywords/UniqueItems.php (hunk 7 above)
Comment (lezhnev74) [reply src/Schema/Keywords/UniqueItems.php:32]: Excellent catch!

File: src/Schema/Validator.php (hunk 8 above)
Comment (lezhnev74) [reply src/Schema/Validator.php:17]: In general, yes, I support this idea. 
That would be a good thing when(if) there would be more arguments to pass in. 
If there is just one thing at the moment (a bread crumb), that looks ok-ish to me.

File: tests/Schema/Keywords/TypeTest.php (hunk 9 above)
Comment (lezhnev74) [reply tests/Schema/Keywords/TypeTest.php:65]: Yeah, looks good

File: src/Schema/Keywords/AnyOf.php (hunk 11 above)
Comment (lezhnev74) [reply src/Schema/Keywords/AnyOf.php]: Another great performance related catch!

**Comment by lezhnev74** [comment]
> ValidationKeywordFailed (I find this naming strange, but didn't touch it)

Please suggest a better name here. 
My intention was explaining exactly what happened - a schema keyword (which is an OpenAPI term(JSON schema)) failed validation against data.

File: src/Schema/Validator.php (hunk 8 above)
Comment (scaytrase) [reply src/Schema/Validator.php:17]: Yea, thats why I call it `future` idea ) Not now for sure

**Comment by scaytrase** [comment]
> Please suggest a better name here.

Well, I'd better start with `KeywordValidationFailed`. But there is no keywod validation, there is data validation. To keep naming style we could use something like `KeywordMismatch` or so, but not sure

File: tests/Schema/Keywords/MultipleOfTest.php (hunk 12 above)
Comment (scaytrase) [reply tests/Schema/Keywords/MultipleOfTest.php:11]: Weird, but fixed. int/int is int if it's divisible, not float. what the hell. added explicit cast to float for comparison

Comment (lezhnev74) [reply tests/Schema/Keywords/MultipleOfTest.php:11]: As it turns out, the result of a division can be both `int` and `float`. It would be better to have `float` as a result of a division in all cases (thought PHP is not there yet).
```php
4/2 === 2; // true
4.0/2 === 2.0; //true
```

**Comment by lezhnev74** [comment]
`KeywordMismatch` looks like a good option. 

There could be other exceptions which extend this one (if we want to report some specific keyword related failure (hence `FormatMismatch -> TypeMismatch -> ValidationKeywordFailed`).

File: tests/Schema/Keywords/MultipleOfTest.php (hunk 12 above)
Comment (scaytrase) [reply tests/Schema/Keywords/MultipleOfTest.php:11]: yeah, that's the thing I did in the fix. Updated it to be more clear

**Comment by lezhnev74** [comment]
I am going to study changes for a day or two, maybe. If nothing major found, then gonna tag `0.13.0`.

**Comment by lezhnev74** [comment]
@scaytrase please review this commit: https://github.com/lezhnev74/openapi-psr7-validator/pull/24/commits/ecfda741315fa1eb2af72f3c5d21be9767d4ab9f

I thought that input validation must be decoupled from "keyword" validation. But now I have doubts as it sometimes calls `SchemaValidator` like here: https://github.com/lezhnev74/openapi-psr7-validator/pull/24/commits/ecfda741315fa1eb2af72f3c5d21be9767d4ab9f#diff-e724b0820a8b3411744e47d319e09430

**Comment by scaytrase** [comment]
> I thought that input validation must be decoupled from "keyword" validation. 

Looks totally valid. I thought about same change but didn't  do it for no reason. As long as `SchemaValidator` keeps it contract defensive validation could be decoupled, as `Respect` exceptions will not pass thru the catch clause and contracts would stay valid and clear

File: src/Schema/Validator.php [hunk 13]
```diff
@@ -4,173 +4,15 @@
...
-use OpenAPIValidation\Schema\Keywords\Required;
-use OpenAPIValidation\Schema\Keywords\Type;
-use OpenAPIValidation\Schema\Keywords\UniqueItems;
-use function count;
+use cebe\openapi\spec\Schema;
+use OpenAPIValidation\Schema\Exception\SchemaMismatch;
 
-// This will load a whole schema and data to validate if one matches another
-class Validator
+interface Validator
```
Comment (lezhnev74) [inline src/Schema/Validator.php:10]: Can you explain the logic behind extracting this interface from the `SchemaValidator`? Looks like it is not used anywhere.

Comment (scaytrase) [reply src/Schema/Validator.php:10]: Well, at least it can be used as a library public contract, allowing to mock it easily. I have other ideas but not sure about them

Comment (lezhnev74) [reply src/Schema/Validator.php:10]: It does not look like the implementation can be swapped with something else. I don't mind this interface, I wonder what are the other possible cases?

Comment (scaytrase) [reply src/Schema/Validator.php:10]: well, it could be mocked and decorated using the interface. currently there is no points of extension for this class, so even we definalize it back in order to mock or decorate it we will get only FQCN and method signature. It's called interface, so I extracted it explicitly.

My other thoughts are about looking at other nested validator. Most of them really have the same signature, but a bit smudged. In general they take the a portion of `data` and the `schema` in some way and compare one with another. So signature (inlc. exceptions) stays the same.

If we incapsulate keyword knowledge into the keyword validator itself (like moving `isset` check inside it) and pass not keyword options but schema object - we will create incapsulated validators with the same signature, which has all knowled about data validation

Comment (lezhnev74) [reply src/Schema/Validator.php:10]: Sounds good to me

**Comment by scaytrase** [comment]
I'll point to PSR-7 namespace consistency a bit later. I hope there will be similar changes.
