### PR TITLE
Use data type only for type exceptions

### LINKED ISSUE #19: Invalid invalid type handling
If data type does not match schema code still tries to utilize it as a scalar value. moreother it tries utilize value itself rather than type, and this can lead to huge error texts

```
notice: "Array to string conversion in /data/www/content.leos.lamoda.ru/vendor/lezhnev74/openapi-psr7-validator/src/Schema/Keywords/Type.php on line 81"
```

I'll try to fix it

### PR DESCRIPTION
**Pull request by scaytrase**
Fixes #19

### CODE REVIEW

File: src/Foundation/ArrayHelper.php [hunk 1]
```diff
@@ -17,15 +17,13 @@ final class ArrayHelper
...
-     * @param mixed[] $arr
      */
     public static function isAssoc(array $arr) : bool
     {
         if ($arr === []) {
             return false;
         }
 
-        return array_keys($arr) === range(0, count($arr) - 1);
+        return array_keys($arr) !== range(0, count($arr) - 1);
```
Comment (scaytrase) [inline src/Foundation/ArrayHelper.php:29]: This one was interesting and worked because there was 
```
!(is_array($data) && ArrayHelper::isAssoc($data))
``` 

instead of 

```
!is_array($data) || ArrayHelper::isAssoc($data)
```

Comment (lezhnev74) [reply src/Foundation/ArrayHelper.php:29]: Makes sense!

File: src/Schema/Keywords/Type.php [hunk 2]
```diff
@@ -38,56 +39,44 @@ class Type extends BaseKeyword
...
-                0 => 'boolean',
-                1 => 'object',
-                2 => 'array',
-                3 => 'number',
-                4 => 'integer',
-                5 => 'string',
-                // Note that there is no null type; instead, the nullable attribute is used as a modifier of the base type.
-            ])->stringType()->assert($type);
-
             if ($this->parentSchema->nullable && $data === null) {
```
Comment (scaytrase) [inline src/Schema/Keywords/Type.php]: should we skip this also? we've fixed this recently, didn't we? in another place

Comment (lezhnev74) [reply src/Schema/Keywords/Type.php]: Indeed, we did solve it here: `src/Schema/Validator.php` on lines 68-73. 
Looks like this is safe to remove.

Comment (scaytrase) [reply src/Schema/Keywords/Type.php]: Removed

File: src/Schema/Exception/InvalidSchemaException.php [hunk 3]
```diff
@@ -0,0 +1,11 @@
+<?php
+
+declare(strict_types=1);
+
+namespace OpenAPIValidation\Schema\Exception;
+
+use Exception;
+
+class InvalidSchemaException extends Exception
```
Comment (lezhnev74) [inline src/Schema/Exception/InvalidSchemaException.php]: This class is not used anywhere. Is it there for upcoming changes?

File: src/Schema/Keywords/Type.php [hunk 4]
```diff
@@ -38,56 +37,40 @@ class Type extends BaseKeyword
...
                     if (! is_bool($data)) {
-                        throw new Exception(sprintf("Value '%s' is not a boolean", $data));
+                        throw TypeException::becauseTypeDoesNotMatch(CebeType::BOOLEAN, $data);
                     }
                     break;
-                case 'object':
+                case CebeType::OBJECT:
                     if (! is_object($data) && ! is_array($data)) {
-                        throw new Exception(sprintf("Value '%s' is not an object", $data));
+                        throw TypeException::becauseTypeDoesNotMatch(CebeType::OBJECT, $data);
```
Comment (lezhnev74) [inline src/Schema/Keywords/Type.php]: I like how it looks, `throw X::becauseY`. Will steal it :)

File: src/Schema/Exception/InvalidSchemaException.php (hunk 3 above)
Comment (lezhnev74) [reply src/Schema/Exception/InvalidSchemaException.php]: Here is another issue. Doctrine coding standard won't let you name exception as "Exception". You need to remove "Exception" suffix in order to pass the quality checks.

Comment (lezhnev74) [reply src/Schema/Exception/InvalidSchemaException.php]: I am going to update CI config to run these checks automatically for each new PR

**Comment by lezhnev74** [comment]
Pushed some minor fixes to pass Doctrine coding style checks.

File: src/Schema/Exception/InvalidSchemaException.php (hunk 3 above)
Comment (scaytrase) [reply src/Schema/Exception/InvalidSchemaException.php]: Nah, we just removed it's only usage in one of "too defencive checks". Will clean it up

File: src/Schema/Keywords/Type.php (hunk 4 above)
Comment (scaytrase) [reply src/Schema/Keywords/Type.php]: Yeah, we using in our team. Looks nice, but not in 100% cases

File: src/Schema/Exception/InvalidSchemaException.php (hunk 3 above)
Comment (scaytrase) [reply src/Schema/Exception/InvalidSchemaException.php]: Removed

File: src/Schema/Exception/TypeMismatch.php [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+namespace OpenAPIValidation\Schema\Exception;
+
+use Exception;
+use function gettype;
+use function sprintf;
+
+class TypeMismatch extends Exception
+{
+    /**
+     * @param mixed $value
```
Comment (scaytrase) [inline src/Schema/Exception/TypeMismatch.php:14]: Do we really need `mixed` typehint everywhere? It does not bring any new info

Comment (lezhnev74) [reply src/Schema/Exception/TypeMismatch.php:14]: Good question. Doctrine REQUIRES us to provide at least something about "untyped" values. It would be better to provide a type, but there can be anything, actually. So If I remove this, doctrine checks fail...

Comment (scaytrase) [reply src/Schema/Exception/TypeMismatch.php:14]: Ehh, okay

**Comment by scaytrase** [comment]
Looks like every comment is addressed

**Comment by lezhnev74** [comment]
Merged. Gonna update Readme with mentions of a new exception class.

**Comment by scaytrase** [comment]
Is it needed? It's currently being rethrown as `ValidationKeywordFailed` as before

**Comment by lezhnev74** [comment]
Well, currently you should be able to evaluate "previous" exceptions chain. So it could be valuable in some situations.
