### PR TITLE
Exceptions consistency pt. 2

### LINKED ISSUE #18: Exceptions consistency
Here I will create a list of inconsistent exceptions or exception hierarchy:

 - [x]  (https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Keywords/Type.php#L113)[FormatMismatch] exception is derived from `\LogicException`, which according [to the manual](https://www.php.net/manual/en/class.logicexception.php) happens only if code logic is broken and there is a bug or misbehaviour in the library
 - [x] Same stands for `ValidationKeywordFailed`
 - [x] I'm not sure there is sense in catching any `\Throwable` since it too broad (i.e it would catch `\ParseError` and convert it to `KeywordValidationFailed` too)
 - [ ] Most other exceptions are derived from `\RuntimeException`, like `MissedRequestCookie`
 - [ ] `MultipleOperationsMismatchForRequest` extends `Exception` this looks correct but misaligned with other exceptions :)

Notes: `\LogicException` and `\RuntimeException` are kind of ["Unchecked exceptions"](https://crunchify.com/better-understanding-on-checked-vs-unchecked-exceptions-how-to-handle-exception-better-way-in-java/) analogue in PHP and they are often [excluded from IDE static analisys by default](https://blog.jetbrains.com/phpstorm/2018/04/configurable-unchecked-exceptions/)

### PR DESCRIPTION
**Pull request by scaytrase**
Second part of exception consistency (fixes #18)

I've got some spare time, so here is some improvements:

- [x] Generic validation exception signature (all validators now declare exceptions they will throw, incl. top-level request and response validators)
- [x] Consistent exception hierarchy
- [x] More precise exception rethrow control - switch-case rethrow will not catch unintended exceptions now
- [x] Make inner validators throw needed exceptions directly (get rid of magic error codes and additional switch-cases)
- [x] Update docs with new exceptions (I noticed there was no BreadCrumb usage example in the readme, probably this PR is a good place to add it)

### CODE REVIEW

**Comment by scaytrase** [comment]
@lezhnev74 do we really need duplicated set of exceptions? I see only reason in having detailed exception message, but I have ideas how to overcome it without having separate exceptions for request and response 

https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR7/Exception/Request/RequestBodyMismatch.php
https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR7/Exception/Response/ResponseBodyMismatch.php

for me they looks exactly same, but with response code added.

combining them into one would simplify a lot validation process

**Comment by scaytrase** [comment]
I thinkI'm ready for review

**Comment by scaytrase** [comment]
I'll update docs with new changes after they will be approved with separate commit

**Comment by lezhnev74** [comment]
Awesome! 
I will take a good look at this PR asap.

File: src/PSR7/Exception/Validation/InvalidBody.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+class InvalidBody extends AddressValidationFailed
+{
+    public static function becauseBodyDoesNotMatchSchema(
+        string $contentType,
+        OperationAddress $addr,
+        SchemaMismatch $prev
+    ) : self {
+        $exception          = static::fromAddrAndPrev($addr, $prev);
+        $exception->message = sprintf('Body does not match schema for content-type "%s" for %s', $contentType, $addr);
```
Comment (scaytrase) [inline src/PSR7/Exception/Validation/InvalidBody.php:19]: I'm not sure for `SchemaMismatch` whether I should leave generic message and use `prev` for deep inspections or prepend prev message instead of generic text. I'll try both ways a bit later

File: src/PSR7/OperationAddress.php [hunk 2]
```diff
@@ -4,24 +4,103 @@
 
 namespace OpenAPIValidation\PSR7;
 
-class OperationAddress extends PathAddress
```
Comment (scaytrase) [inline src/PSR7/OperationAddress.php:7]: I did not find the place where `PathAddress` was used on its own, only as `OperationAddress` or below. These changes made usage a bit simpler, since in most cases static methods were called on `OperationAddress` instance parts, so it was easier to call these methods on instance itself

File: src/PSR7/OperationAddress.php [hunk 3]
```diff
@@ -4,24 +4,103 @@
...
+
+        return (bool) preg_match($pattern, $path);
+    }
+
     public function method() : string
     {
         return $this->method;
     }
 
-    public function getOperationAddress() : self
```
Comment (scaytrase) [inline src/PSR7/OperationAddress.php:23]: I remove casting method, since there is no sence in it. Class is immutable VO and successors can use it signature without casting

File: src/PSR7/ServerRequestValidator.php [hunk 4]
```diff
@@ -4,50 +4,41 @@
...
+    /** @var MessageValidator */
+    protected $validator;
 
     public function __construct(OpenApi $schema)
     {
-        $this->openApi = $schema;
-        $this->finder  = new SpecFinder($this->openApi);
+        $this->openApi   = $schema;
+        $finder          = new SpecFinder($this->openApi);
+        $this->validator = new ValidatorChain(
```
Comment (scaytrase) [inline src/PSR7/ServerRequestValidator.php:34]: Most important changes here. I've replace class methods with validator chain with separate validators. I have some thoughts about configuring the chain outside of the class, but not in this PR

File: src/PSR7/SpecFinder.php [hunk 5]
```diff
@@ -52,12 +66,129 @@ public function findPathSpec(PathAddress $addr) : PathItem
...
     }
 
+    /**
+     * @return Parameter[]
+     *
+     * @throws NoPath
+     */
+    public function findPathSpecs(OperationAddress $addr) : array
+    {
+        $spec = $this->findOperationSpec($addr);
```
Comment (scaytrase) [inline src/PSR7/SpecFinder.php:76]: I moved spec extracting to this class as is (with comments, etc). I think this class suits for such methods

File: tests/PSR7/ServerRequestTest.php [hunk 6]
```diff
@@ -58,44 +56,36 @@ public function testItValidatesBodyHasUnexpectedTypeRed() : void
             ->withoutHeader('Content-Type')
             ->withHeader('Content-Type', 'unexpected/content');
 
-        try {
-            $validator = (new ValidatorBuilder())->fromYamlFile($this->apiSpecFile)->getServerRequestValidator();
-            $validator->validate($request);
```
Comment (scaytrase) [inline tests/PSR7/ServerRequestTest.php:63]: This also fixed some tests - some have missing `$this->fail`. Also expecting expection directly is more preferred flow, I think

File: src/PSR7/OperationAddress.php [hunk 7]
```diff
@@ -4,24 +4,103 @@
...
+    public function __toString() : string
+    {
+        return sprintf('Request [%s %s]', $this->method, $this->path);
```
Comment (scaytrase) [inline src/PSR7/OperationAddress.php:49]: i found this notation more readable (like `[post /some/method]` for request and `[post /some/method 200]` for response). But this is debatable

File: src/PSR7/ServerRequestValidator.php [hunk 8]
```diff
@@ -96,251 +89,17 @@ public function validate(ServerRequestInterface $serverRequest) : OperationAddre
...
     /**
-     * @throws TypeErrorException
+     * Check the openapi spec and find matching operations(path+method)
+     * This should consider path parameters as well
+     * "/users/12" should match both ["/users/{id}", "/users/{group}"]
+     *
+     * @return OperationAddress[]
      */
-    protected function validateHeaders(OperationAddress $addr, ServerRequestInterface $serverRequest) : void
+    private function findMatchingOperations(ServerRequestInterface $request) : array
```
Comment (scaytrase) [inline src/PSR7/ServerRequestValidator.php:99]: I found this function was used privately by this class, so moved it here from specfinder, since it is not really specs, but path matching (aka routing)

File: src/PSR7/Validators/SecurityValidator.php [hunk 9]
```diff
@@ -0,0 +1,183 @@
...
+     */
+    private function validateApiKeySecurityScheme(
+        OperationAddress $addr,
+        ServerRequestInterface $request,
+        SecurityScheme $securityScheme
+    ) : void {
+        switch ($securityScheme->in) {
+            case 'query':
+                if (! isset($request->getQueryParams()[$securityScheme->name])) {
+                    throw InvalidQueryArgs::becauseOfMissingRequiredArgument($securityScheme->name, $addr);
```
Comment (scaytrase) [inline src/PSR7/Validators/SecurityValidator.php:168]: Now every validation throws meaningful exception direclty

File: src/PSR7/ResponseValidator.php [hunk 10]
```diff
@@ -5,74 +5,42 @@
...
+    /** @var MessageValidator */
+    protected $validator;
 
     public function __construct(OpenApi $schema)
     {
-        $this->openApi = $schema;
-        $this->finder  = new SpecFinder($this->openApi);
+        $this->openApi   = $schema;
+        $finder          = new SpecFinder($this->openApi);
+        $this->validator = new ValidatorChain(
```
Comment (scaytrase) [inline src/PSR7/ResponseValidator.php:25]: This class is now very tiny, since all validators are moved away. I hope we can create something like `GuidedServerRequestValidator` which does not perform path matching (aka routing) and accepts PathOperation with arguments and it will be the same tiny class as this one

**Comment by scaytrase** [comment]
@lezhnev74 did you have a chance to look a this PR?

**Comment by lezhnev74** [comment]
Not really, sorry about the delay. 
I want to allocate a proper amount of time to get into it but I am super busy these days. 
I think, this weekend I ll do this.

**Comment by scaytrase** [comment]
Sure, no problems

**Comment by lezhnev74** [comment]
I surfed over the changes and they look good to me. 👍 
The codebase got much more predictable in terms of exceptions. 
I did not see anything unexpected or questionable so far. Let me play with it for the weekend.

**Comment by lezhnev74** [comment]
So far so good. I am going to focus on #44 as this part of the validation works not so good. I am going to base it on this codebase, so feel free to update the readme and let's merge this in.

**Comment by scaytrase** [comment]
I've updated readme and do some minor exception moves (found while writing readme). But there is a conflict with your latest changes. Should I resolve it or you'll do it while merge?

**Comment by lezhnev74** [comment]
Yeah, since you are deeply into this, can you do the conflict resolution yourself?

**Comment by scaytrase** [comment]
All green

**Comment by lezhnev74** [comment]
Ok, let me tag this
